### ISSUE TITLE
Define Pvlan Id to Guest

### ISSUE THREAD

**Issue by f1rstsurf** [vmware/pyvmomi#950]
Hi, 

i'm currently working on a project, to automate VM deployment, based on template. To proceed I'm using Ansible 2.10, and Pyvmomi  7.0.1.

I'm facing an issue trying to define a Pvlan id (51), to my guest, here's my playbook : 

```
networks:
      - vlan: 51
        ip: 100.64.67.13
        netmask: 255.255.240.0
        type: static
```

But I keep getting the following error : 
`AttributeError: 'vim.dvs.VmwareDistributedVirtualSwitch.PvlanSpec' object has no attribute 'vlanId'`

I already checked my user permissions on Vswitch, Datastore an VM, nothing to declare on this side.
